/**
 * @fileoverview Terms of Service page component
 */

import React from 'react';
import { Link } from 'react-router-dom';

/**
 * Terms of Service page component
 * @returns {JSX.Element} Terms of Service page component
 */
const TermsPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold text-secondary-800 mb-6">Terms of Service</h1>
      
      <div className="bg-blue-50 border border-blue-200 rounded-md p-4 mb-8">
        <p className="text-blue-800">
          <strong>Last Updated:</strong> April 1, 2023
        </p>
      </div>
      
      <div className="prose prose-lg max-w-none">
        <p>
          These Terms of Service ("Terms") govern your use of the Yard Renovator web application 
          operated by Yard Renovator, Inc. ("we," "our," or "us"). By accessing or using the 
          Yard Renovator application, you agree to be bound by these Terms. If you disagree with 
          any part of the Terms, then you may not access the application.
        </p>
        
        <h2>1. Accounts</h2>
        <p>
          When you create an account with us, you must provide information that is accurate, complete, 
          and current at all times. Failure to do so constitutes a breach of the Terms, which may result 
          in immediate termination of your account.
        </p>
        <p>
          You are responsible for safeguarding your account and for any activities or actions under your account.
          We use Google authentication, and you should ensure your Google account credentials remain secure.
        </p>
        
        <h2>2. Subscription and Payments</h2>
        <p>
          Yard Renovator operates on a credit-based system. Credits can be purchased through our payment 
          processor, PayPal. Each credit allows you to generate one AI renovation of a yard image.
        </p>
        <p>
          All purchases are final and non-refundable, except as required by applicable law. Credits do not 
          expire once purchased. We reserve the right to modify our pricing at any time, but existing purchased 
          credits will maintain their value.
        </p>
        
        <h2>3. User Content</h2>
        <p>
          Our application allows you to upload content, specifically images of yards for renovation purposes. 
          You retain all rights to the images you upload to the service.
        </p>
        <p>
          By uploading content to Yard Renovator, you grant us a non-exclusive, worldwide, royalty-free license 
          to use, reproduce, and process your content solely for the purpose of providing our services to you, 
          including generating AI renovations and displaying both the original and renovated images in your account.
        </p>
        <p>
          You represent and warrant that:
        </p>
        <ul>
          <li>You own or have the rights to the content you upload</li>
          <li>The content does not violate the privacy rights, publicity rights, copyrights, or other rights of any person</li>
          <li>The content does not contain any material that could be considered harmful, threatening, unlawful, 
              defamatory, obscene, or otherwise objectionable</li>
        </ul>
        
        <h2>4. AI-Generated Content</h2>
        <p>
          The renovations generated by our AI are provided for visualization and inspiration purposes only. 
          We make no guarantees regarding the feasibility, accuracy, or appropriateness of the generated renovations.
        </p>
        <p>
          You own the right to use the AI-generated renovations created for you, but you acknowledge that similar 
          renovations may be generated for other users due to the nature of the AI technology we use.
        </p>
        
        <h2>5. Product Recommendations</h2>
        <p>
          As part of our service, we may recommend products available on Amazon or other retailers based on your 
          renovation results. These recommendations include affiliate links, which means we may earn a commission 
          if you make a purchase through these links.
        </p>
        <p>
          We do not guarantee the availability, quality, or suitability of recommended products. You should perform 
          your own research before purchasing any recommended products.
        </p>
        
        <h2>6. Intellectual Property</h2>
        <p>
          The Yard Renovator application and its original content, features, and functionality are and will remain 
          the exclusive property of Yard Renovator, Inc. and its licensors. The application is protected by copyright, 
          trademark, and other laws of the United States and foreign countries.
        </p>
        <p>
          Our trademarks and trade dress may not be used in connection with any product or service without the prior 
          written consent of Yard Renovator, Inc.
        </p>
        
        <h2>7. Limitation of Liability</h2>
        <p>
          In no event shall Yard Renovator, Inc., nor its directors, employees, partners, agents, suppliers, or 
          affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including 
          without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from:
        </p>
        <ul>
          <li>Your access to or use of or inability to access or use the service</li>
          <li>Any conduct or content of any third party on the service</li>
          <li>Any content obtained from the service</li>
          <li>Unauthorized access, use, or alteration of your transmissions or content</li>
          <li>Implementation of any renovations suggested by our application</li>
        </ul>
        
        <h2>8. Termination</h2>
        <p>
          We may terminate or suspend your account immediately, without prior notice or liability, for any reason 
          whatsoever, including without limitation if you breach the Terms.
        </p>
        <p>
          Upon termination, your right to use the application will immediately cease. If you wish to terminate your 
          account, you may simply discontinue using the application or contact us to request account deletion.
        </p>
        
        <h2>9. Changes to Terms</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will make 
          reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect. By continuing 
          to access or use our application after those revisions become effective, you agree to be bound by the revised terms.
        </p>
        
        <h2>10. Governing Law</h2>
        <p>
          These Terms shall be governed and construed in accordance with the laws of the United States, without 
          regard to its conflict of law provisions.
        </p>
        
        <h2>11. Contact Us</h2>
        <p>
          If you have any questions about these Terms, please contact us at:
          <br />
          <a href="mailto:legal@yardrenovator.com" className="text-primary-600 hover:underline">
            legal@yardrenovator.com
          </a>
        </p>
      </div>
      
      <div className="mt-12 text-center">
        <p className="text-secondary-600 mb-4">
          By using Yard Renovator, you acknowledge that you have read and understood these Terms of Service.
        </p>
        <div className="flex justify-center gap-4">
          <Link to="/privacy" className="text-primary-600 hover:underline">Privacy Policy</Link>
          <Link to="/about" className="text-primary-600 hover:underline">About Us</Link>
          <Link to="/contact" className="text-primary-600 hover:underline">Contact</Link>
        </div>
      </div>
    </div>
  );
};

export default TermsPage; 